services:
  db:
    image: postgres:17
    restart: always
  
    environment:
      POSTGRES_DB: Url_Shortner
      POSTGRES_USER: Aditrii
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 